#pragma comment(linker, "/export:__Aligned_get_default_resource=msvcp140_1d._Aligned_get_default_resource") 
#pragma comment(linker, "/export:__Aligned_new_delete_resource=msvcp140_1d._Aligned_new_delete_resource") 
#pragma comment(linker, "/export:__Aligned_set_default_resource=msvcp140_1d._Aligned_set_default_resource") 
#pragma comment(linker, "/export:__Unaligned_get_default_resource=msvcp140_1d._Unaligned_get_default_resource") 
#pragma comment(linker, "/export:__Unaligned_new_delete_resource=msvcp140_1d._Unaligned_new_delete_resource") 
#pragma comment(linker, "/export:__Unaligned_set_default_resource=msvcp140_1d._Unaligned_set_default_resource") 
#pragma comment(linker, "/export:_null_memory_resource=msvcp140_1d.null_memory_resource") 
